name: Static Gnuplot Build

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            autoconf automake libtool \
            pkg-config \
            libgd-dev \
            libreadline-dev \
            liblua5.2-dev \
            libwxgtk3.2-dev \
            libxcb-xinerama0-dev \
            qtbase5-dev \
            zlib1g-dev \
            libx11-dev \
            libxpm-dev \
            libjpeg-dev \
            libpng-dev \
            libfreetype6-dev

      - name: Configure and build (Linux)
        if: runner.os == 'Linux'
        run: |
          ./prepare
          ./configure \
            --enable-static \
            --disable-shared \
            --with-readline=gnu \
            --without-latex \
            --without-gd \
            --without-qt \
            --without-wx \
            --without-x \
            --without-lua \
            --without-cairo \
            --disable-wxt \
            --disable-x11 \
            --disable-qt \
            --disable-gpic \
            --disable-gd \
            --disable-latex \
            LDFLAGS="-static" \
            CFLAGS="-O2"
          make -j$(nproc)

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install \
            autoconf automake libtool pkg-config \
            gd readline lua qt

      - name: Configure and build (macOS)
        if: runner.os == 'macOS'
        run: |
          ./prepare
          ./configure \
            --enable-static \
            --disable-shared \
            --with-readline=gnu \
            --without-latex \
            --without-gd \
            --without-qt \
            --without-wx \
            --without-x \
            --without-lua \
            --without-cairo \
            --disable-wxt \
            --disable-x11 \
            --disable-qt \
            --disable-gpic \
            --disable-gd \
            LDFLAGS="-static" \
            CFLAGS="-O2"
          make -j$(sysctl -n hw.logicalcpu)

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-make
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-libtool
            mingw-w64-x86_64-readline
            mingw-w64-x86_64-zlib
            mingw-w64-x86_64-libpng
            mingw-w64-x86_64-libjpeg-turbo
            mingw-w64-x86_64-freetype
            mingw-w64-x86_64-cairo
            base-devel

      - name: Configure and build (Windows)
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: |
          ./prepare
          ./configure \
            --host=x86_64-w64-mingw32 \
            --enable-static \
            --disable-shared \
            --without-gd \
            --without-qt \
            --without-wx \
            --without-x \
            --without-lua \
            --without-cairo \
            --disable-wxt \
            --disable-x11 \
            --disable-qt \
            --disable-gpic \
            --disable-gd \
            --disable-latex \
            CFLAGS="-static -O2" \
            LDFLAGS="-static"
          make -j$(nproc)
